export const environment = {
  production: true,
  baseUrl: "http://localhost:55279/",
  categoriesUrl: "category/",
  orderUrl: "orders/",
  availableOrdersUrl: "available/",
  completedOrdersUrl: "completed/",
  productsUrl: "products/",
  usersUrl: "users/",
  userRegisterUrl: "register/",
  userLoginUrl: "authenticate/",
  statisticsUrl: "stats/",
  totalWorthUrl: "totalworth/",
  couriersUrl: "couriers/",
};
