export const environment = {
  production: true,
  baseUrl: 'http://86.105.51.156:4301/',
  categoriesUrl: "category/",
  orderUrl: "orders/",
  availableOrdersUrl: "available/",
  completedOrdersUrl: "completed/",
  productsUrl: "products/",
  usersUrl: "users/",
  userRegisterUrl: "register/",
  userLoginUrl: "authenticate/",
  statisticsUrl: 'stats/',
  totalWorthUrl: 'totalworth/',
  couriersUrl: "couriers/",
};
